apiVersion: v1
kind: Template
metadata:
  name: postgres
  annotations:
    description: "Thoth: PGWeb"
    openshift.io/display-name: "Thoth: PGWeb"
    version: 0.4.2
    tags: thoth,ai-stacks,postgresql,pgweb
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines PGWeb needed to browse PostgreSQL content in Thoth on OpenShift.
    template.openshift.io/provider-display-name: "Red Hat, Inc."
  labels:
    app: thoth-postgres
    component: postgres

objects:

- kind: Route
  apiVersion: v1
  metadata:
    name: pgweb
    labels:
      app: thoth-postgres
      component: pgweb
  spec:
    to:
      kind: Service
      name: pgweb

- kind: Service
  apiVersion: v1
  metadata:
    labels:
      service: pgweb
      app: thoth-postgres
      component: pgweb
    name: pgweb
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8081
    selector:
      service: pgweb

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: pgweb
      app: thoth-postgres
      component: pgweb
    name: pgweb
  spec:
    replicas: 1
    selector:
      service: pgweb
    template:
      metadata:
        labels:
          service: pgweb
      spec:
        containers:
        - env:
          - name: DB_HOST
            value: postgresql
          - name: DB_PORT
            value: "5432"
          - name: DB_DATABASE
            value: "${POSTGRESQL_DATABASE}"
          - name: DB_USER
            value: "${POSTGRESQL_USER}"
          - name: DB_PASSWORD
            value: "${POSTGRESQL_PASSWORD}"
          name: pgweb
          ports:
            - containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "1"
            limits:
              memory: "512Mi"
              cpu: "1"
          readinessProbe:
            httpGet:
              path: '/'
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: '/'
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 10
    test: false
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - pgweb
        from:
          kind: ImageStreamTag
          name: 'pgweb:latest'

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: pgweb
    labels:
      app: thoth-postgres
      component: pgweb
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: sosedoff/pgweb:0.11.3
      name: latest

parameters:
  - description: "Database used to store data"
    displayName: "PosgtreSQL database name"
    name: POSTGRESQL_DATABASE
    required: true
    value: "thoth"

  - description: "Database password"
    displayName: "PosgtreSQL database password"
    name: POSTGRESQL_PASSWORD
    required: true
    value: "thoth"

  - description: "Database user"
    displayName: "PosgtreSQL database user"
    name: POSTGRESQL_USER
    required: true
    value: "thoth"
